<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class WasteCategoriesSeeder extends Seeder
{
    public function run()
    {
        $categories = [
            [
                'class_name' => 'Elektronik',
                'category' => 'B3',
                'info' => "Limbah elektronik, juga dikenal sebagai e-waste, adalah peralatan elektronik yang sudah tidak digunakan atau rusak. Ini mencakup komputer, ponsel, televisi, dan perangkat elektronik lainnya. Limbah elektronik mengandung berbagai bahan berbahaya seperti timbal, merkuri, dan kadmium yang dapat mencemari lingkungan jika tidak ditangani dengan benar. Namun, limbah elektronik juga mengandung bahan berharga seperti emas, perak, dan tembaga yang dapat didaur ulang. Pengelolaan limbah elektronik yang tepat sangat penting untuk melindungi lingkungan dan kesehatan manusia, serta untuk memulihkan sumber daya berharga.",
                'handling_info' => "- Kumpulkan limbah elektronik secara terpisah dari sampah rumah tangga lainnya.\n- Bawa ke pusat daur ulang elektronik resmi atau program take-back produsen.\n- Jangan membuang limbah elektronik ke tempat sampah biasa atau membakarnya.\n- Hapus semua data pribadi dari perangkat sebelum mendaur ulang.\n- Pertimbangkan untuk memperbaiki atau menjual perangkat yang masih berfungsi.",
                'environmental_impact' => 'Tinggi',
                'recycling_potential' => 'Tinggi - Banyak komponen dapat didaur ulang untuk menghasilkan bahan baku baru.',
                'decomposition_time' => 'Tidak terurai secara alami, tetapi dapat bertahan ratusan tahun di tempat pembuangan sampah.',
                'reduction_tips' => "- Perpanjang umur perangkat elektronik dengan perawatan yang baik.\n- Beli perangkat elektronik yang tahan lama dan dapat diperbaiki.\n- Pilih produk dengan sertifikasi ramah lingkungan.\n- Sewa atau pinjam peralatan elektronik yang jarang digunakan.\n- Donasikan perangkat yang masih berfungsi.",
                'other_examples' => 'Printer, mesin cuci, microwave, konsol game, baterai lithium-ion',
                'regulations' => 'Peraturan Pemerintah Republik Indonesia Nomor 101 Tahun 2014 tentang Pengelolaan Limbah Bahan Berbahaya dan Beracun',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Biologis',
                'category' => 'Organik',
                'info' => "Limbah biologis adalah material organik yang berasal dari makhluk hidup, baik tumbuhan maupun hewan. Ini mencakup sisa makanan, daun, rumput, dan kotoran hewan. Limbah biologis umumnya mudah terurai secara alami dan dapat dikompos untuk menghasilkan pupuk organik yang kaya nutrisi. Pengelolaan limbah biologis yang tepat dapat mengurangi volume sampah yang dikirim ke tempat pembuangan akhir, mengurangi emisi gas rumah kaca, dan menghasilkan sumber daya yang bermanfaat untuk pertanian dan perkebunan.",
                'handling_info' => "- Pisahkan limbah biologis dari jenis sampah lainnya.\n- Kompos di rumah jika memungkinkan, atau kirim ke fasilitas pengomposan komunal.\n- Hindari mencampur dengan bahan non-organik.\n- Jika mengompos di rumah, pastikan tumpukan kompos memiliki keseimbangan yang baik antara bahan 'hijau' (kaya nitrogen) dan 'cokelat' (kaya karbon).\n- Gunakan hasil kompos sebagai pupuk untuk tanaman.",
                'environmental_impact' => 'Rendah',
                'recycling_potential' => 'Tinggi - Dapat dikompos menjadi pupuk organik yang bermanfaat.',
                'decomposition_time' => 'Beberapa minggu hingga beberapa bulan, tergantung pada kondisi.',
                'reduction_tips' => "- Rencanakan makanan dengan baik untuk mengurangi sisa makanan.\n- Gunakan sisa makanan yang masih layak untuk membuat hidangan baru.\n- Mulailah berkebun di rumah dan gunakan kompos yang dihasilkan.\n- Donasikan makanan berlebih yang masih layak ke bank makanan.\n- Beli buah dan sayur lokal dan musiman untuk mengurangi limbah kemasan.",
                'other_examples' => 'Kulit buah, ampas kopi, cangkang telur, serbuk gergaji, rambut',
                'regulations' => 'Peraturan Menteri Negara Lingkungan Hidup Nomor 13 Tahun 2012 tentang Pedoman Pelaksanaan Reduce, Reuse, dan Recycle melalui Bank Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Plastik',
                'category' => 'Anorganik',
                'info' => "Plastik adalah material sintetis yang terbuat dari polimer. Plastik banyak digunakan karena sifatnya yang ringan, tahan lama, dan murah. Namun, sifat tahan lamanya juga menjadi masalah lingkungan karena plastik sulit terurai secara alami. Limbah plastik dapat mencemari tanah, air, dan udara, serta membahayakan kehidupan laut jika berakhir di lautan. Beberapa jenis plastik dapat didaur ulang, tetapi banyak yang berakhir di tempat pembuangan sampah atau mencemari lingkungan. Pengurangan penggunaan plastik sekali pakai dan peningkatan daur ulang plastik sangat penting untuk mengatasi masalah limbah plastik.",
                'handling_info' => "- Pisahkan plastik berdasarkan jenisnya (PET, HDPE, PVC, dll).\n- Bersihkan plastik dari sisa makanan atau kontaminan lainnya.\n- Tekan botol plastik untuk menghemat ruang.\n- Bawa ke pusat daur ulang atau bank sampah.\n- Untuk plastik yang tidak dapat didaur ulang, buang ke tempat sampah anorganik.",
                'environmental_impact' => 'Tinggi',
                'recycling_potential' => 'Sedang - Beberapa jenis plastik dapat didaur ulang, tetapi tidak semua.',
                'decomposition_time' => '450 tahun atau lebih, tergantung pada jenis plastik.',
                'reduction_tips' => "- Gunakan tas belanja yang dapat digunakan kembali.\n- Hindari produk plastik sekali pakai.\n- Pilih produk dengan kemasan minimal atau kemasan yang dapat didaur ulang.\n- Gunakan botol air isi ulang.\n- Pilih produk berbahan alami sebagai alternatif plastik.",
                'other_examples' => 'Kantong plastik, sedotan, kemasan makanan, mainan plastik, peralatan makan plastik sekali pakai',
                'regulations' => 'Peraturan Presiden Nomor 83 Tahun 2018 tentang Penanganan Sampah Laut',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Kaca Coklat',
                'category' => 'Anorganik',
                'info' => "Kaca coklat adalah jenis kaca yang umumnya digunakan untuk botol minuman seperti bir atau obat-obatan tertentu. Warna coklat pada kaca berfungsi untuk melindungi isi botol dari sinar UV yang dapat merusak kualitas produk. Kaca coklat, seperti jenis kaca lainnya, dapat didaur ulang tanpa batas tanpa kehilangan kualitas atau kejernihannya. Daur ulang kaca coklat membantu mengurangi penggunaan bahan baku baru, menghemat energi, dan mengurangi limbah yang berakhir di tempat pembuangan sampah.",
                'handling_info' => "- Bilas botol kaca coklat untuk menghilangkan sisa isi.\n- Pisahkan tutup botol (biasanya terbuat dari logam atau plastik).\n- Kumpulkan kaca coklat terpisah dari warna kaca lainnya jika memungkinkan.\n- Hindari memecahkan kaca untuk keamanan.\n- Bawa ke pusat daur ulang atau tempat pengumpulan kaca.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Tinggi - Dapat didaur ulang 100% tanpa kehilangan kualitas.',
                'decomposition_time' => 'Satu juta tahun atau lebih.',
                'reduction_tips' => "- Gunakan botol kaca yang dapat diisi ulang.\n- Pilih produk dalam kemasan kaca daripada plastik jika memungkinkan.\n- Gunakan kembali botol kaca untuk penyimpanan atau proyek kerajinan.\n- Dukung merek yang menggunakan kaca daur ulang dalam produk mereka.",
                'other_examples' => 'Botol bir, botol obat, beberapa jenis botol kecap',
                'regulations' => 'Peraturan Menteri Negara Lingkungan Hidup Nomor 13 Tahun 2012 tentang Pedoman Pelaksanaan Reduce, Reuse, dan Recycle melalui Bank Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Kardus',
                'category' => 'Anorganik',
                'info' => "Kardus adalah material yang terbuat dari kertas tebal atau karton bergelombang. Umumnya digunakan untuk kemasan, pengiriman barang, dan penyimpanan. Kardus merupakan bahan yang ramah lingkungan karena berasal dari sumber daya terbarukan (pohon) dan mudah didaur ulang. Daur ulang kardus membantu mengurangi penebangan pohon, menghemat energi, dan mengurangi limbah di tempat pembuangan sampah. Kardus yang tidak terkontaminasi dapat didaur ulang beberapa kali sebelum serat-seratnya menjadi terlalu pendek untuk diproses kembali.",
                'handling_info' => "- Ratakan atau lipat kardus untuk menghemat ruang.\n- Pisahkan pita perekat, staples, atau elemen plastik jika ada.\n- Pastikan kardus bersih dan kering, hindari kardus yang terkontaminasi minyak atau makanan.\n- Kumpulkan bersama dengan kertas untuk didaur ulang.\n- Untuk kardus besar, potong menjadi bagian yang lebih kecil jika diperlukan.",
                'environmental_impact' => 'Rendah',
                'recycling_potential' => 'Tinggi - Dapat didaur ulang menjadi kardus baru atau produk kertas lainnya.',
                'decomposition_time' => '2 bulan dalam kondisi ideal, tetapi bisa lebih lama di tempat pembuangan sampah.',
                'reduction_tips' => "- Gunakan kembali kotak kardus untuk penyimpanan atau pengiriman.\n- Pilih produk dengan kemasan minimal atau tanpa kemasan tambahan.\n- Gunakan tas belanja yang dapat dipakai ulang daripada kardus sekali pakai.\n- Kompos kardus yang tidak dilapisi jika fasilitas daur ulang tidak tersedia.",
                'other_examples' => 'Kotak sepatu, kotak pizza (jika tidak berminyak), kemasan makanan kering, tube dari roll tisu toilet',
                'regulations' => 'Peraturan Menteri Negara Lingkungan Hidup Nomor 13 Tahun 2012 tentang Pedoman Pelaksanaan Reduce, Reuse, dan Recycle melalui Bank Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Tekstil',
                'category' => 'Anorganik',
                'info' => "Limbah tekstil mencakup semua jenis kain dan pakaian yang sudah tidak digunakan lagi. Ini termasuk pakaian bekas, kain perca, handuk, sprei, dan produk tekstil lainnya. Industri tekstil adalah salah satu penyumbang limbah terbesar di dunia, dengan banyak pakaian yang berakhir di tempat pembuangan sampah. Tekstil sintetis seperti poliester dapat membutuhkan waktu ratusan tahun untuk terurai dan melepaskan mikroplastik ke lingkungan. Di sisi lain, tekstil alami seperti katun dan wol lebih ramah lingkungan tetapi tetap memerlukan pengelolaan yang tepat.",
                'handling_info' => "- Pisahkan tekstil berdasarkan jenisnya (katun, wol, sintetis, dll) jika memungkinkan.\n- Cuci dan keringkan tekstil sebelum didaur ulang atau disumbangkan.\n- Sumbangkan pakaian dan tekstil yang masih layak pakai ke badan amal atau toko barang bekas.\n- Bawa tekstil yang tidak layak pakai ke pusat daur ulang tekstil.\n- Gunakan kain perca untuk kerajinan atau lap pembersih.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Sedang - Beberapa tekstil dapat didaur ulang menjadi serat baru atau produk non-tekstil.',
                'decomposition_time' => 'Bervariasi, dari beberapa bulan untuk katun alami hingga lebih dari 200 tahun untuk beberapa serat sintetis.',
                'reduction_tips' => "- Beli pakaian berkualitas yang tahan lama.\n- Perbaiki pakaian yang rusak daripada membuangnya.\n- Sewa pakaian untuk acara khusus.\n- Tukar pakaian dengan teman atau keluarga.\n- Beli pakaian bekas atau vintage.",
                'other_examples' => 'Karpet, tirai, tas kain, tali, benang',
                'regulations' => 'Belum ada regulasi khusus untuk limbah tekstil di Indonesia, namun termasuk dalam Undang-Undang Nomor 18 Tahun 2008 tentang Pengelolaan Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Kaca Hijau',
                'category' => 'Anorganik',
                'info' => "Kaca hijau adalah jenis kaca yang umumnya digunakan untuk botol minuman seperti anggur atau minuman berkarbonasi tertentu. Warna hijau pada kaca berfungsi untuk melindungi isi botol dari sinar UV, meskipun tidak seefektif kaca coklat. Seperti jenis kaca lainnya, kaca hijau dapat didaur ulang tanpa batas tanpa kehilangan kualitas atau warnanya. Daur ulang kaca hijau membantu mengurangi penggunaan bahan baku baru, menghemat energi, dan mengurangi limbah yang berakhir di tempat pembuangan sampah.",
                'handling_info' => "- Bilas botol kaca hijau untuk menghilangkan sisa isi.\n- Pisahkan tutup botol (biasanya terbuat dari logam atau plastik).\n- Kumpulkan kaca hijau terpisah dari warna kaca lainnya jika memungkinkan.\n- Hindari memecahkan kaca untuk keamanan.\n- Bawa ke pusat daur ulang atau tempat pengumpulan kaca.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Tinggi - Dapat didaur ulang 100% tanpa kehilangan kualitas.',
                'decomposition_time' => 'Satu juta tahun atau lebih.',
                'reduction_tips' => "- Gunakan botol kaca yang dapat diisi ulang.\n- Pilih produk dalam kemasan kaca daripada plastik jika memungkinkan.\n- Gunakan kembali botol kaca untuk penyimpanan atau proyek kerajinan.\n- Dukung merek yang menggunakan kaca daur ulang dalam produk mereka.",
                'other_examples' => 'Botol anggur, beberapa jenis botol minuman berkarbonasi, botol minyak zaitun',
                'regulations' => 'Peraturan Menteri Negara Lingkungan Hidup Nomor 13 Tahun 2012 tentang Pedoman Pelaksanaan Reduce, Reuse, dan Recycle melalui Bank Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Logam',
                'category' => 'Anorganik',
                'info' => "Limbah logam mencakup berbagai jenis bahan logam yang sudah tidak digunakan lagi, termasuk kaleng makanan, peralatan dapur bekas, komponen elektronik, dan barang logam lainnya. Logam adalah salah satu bahan yang paling mudah dan efisien untuk didaur ulang. Hampir semua jenis logam dapat didaur ulang tanpa batas tanpa kehilangan kualitasnya. Daur ulang logam sangat penting karena dapat menghemat energi dan sumber daya alam yang signifikan dibandingkan dengan produksi logam baru dari bijih.",
                'handling_info' => "- Bersihkan logam dari sisa makanan atau kontaminan lainnya.\n- Pisahkan logam berdasarkan jenisnya (besi, aluminium, tembaga, dll) jika memungkinkan.\n- Tekan kaleng aluminium untuk menghemat ruang.\n- Pisahkan komponen logam dari barang elektronik jika aman untuk dilakukan.\n- Bawa ke pusat daur ulang atau pengumpul logam bekas.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Tinggi - Hampir semua logam dapat didaur ulang tanpa batas.',
                'decomposition_time' => 'Bervariasi, dari 50 tahun untuk kaleng timah hingga 500 tahun atau lebih untuk beberapa jenis logam.',
                'reduction_tips' => "- Gunakan wadah makanan yang dapat digunakan kembali.\n- Perbaiki barang logam yang rusak daripada membuangnya.\n- Pilih produk dengan kemasan minimal atau tanpa kemasan logam jika memungkinkan.\n- Gunakan botol air isi ulang daripada kaleng minuman sekali pakai.\n- Sumbangkan barang logam yang masih berfungsi.",
                'other_examples' => 'Panci dan wajan bekas, peralatan taman, sepeda bekas, komponen mobil',
                'regulations' => 'Peraturan Pemerintah Republik Indonesia Nomor 101 Tahun 2014 tentang Pengelolaan Limbah Bahan Berbahaya dan Beracun (untuk logam berat)',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'class_name' => 'Residu',
                'category' => 'Anorganik',
                'info' => "Residu adalah sisa limbah yang tidak dapat didaur ulang atau dikompos. Ini termasuk berbagai jenis sampah campuran yang sulit dipisahkan atau terlalu terkontaminasi untuk diproses. Meskipun residu akhirnya berakhir di tempat pembuangan sampah, upaya untuk mengurangi jumlahnya sangat penting untuk memperpanjang umur TPA dan mengurangi dampak lingkungan.",
                'handling_info' => "- Pastikan semua bahan yang dapat didaur ulang atau dikompos telah dipisahkan.\n- Kumpulkan residu dalam kantong sampah terpisah.\n- Buang ke tempat sampah umum atau TPA sesuai aturan setempat.\n- Jangan membakar residu karena dapat melepaskan zat berbahaya.",
                'environmental_impact' => 'Tinggi',
                'recycling_potential' => 'Rendah - Sebagian besar tidak dapat didaur ulang.',
                'decomposition_time' => 'Bervariasi, tergantung pada komposisi.',
                'reduction_tips' => "- Pilih produk dengan kemasan minimal atau yang dapat didaur ulang.\n- Hindari produk sekali pakai.\n- Praktikkan pemilahan sampah yang baik untuk mengurangi residu.\n- Beli barang bekas atau perbaiki barang yang rusak.",
                'other_examples' => 'Pembalut, popok sekali pakai, kemasan makanan multilayer, puntung rokok',
                'regulations' => 'Undang-Undang Nomor 18 Tahun 2008 tentang Pengelolaan Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Kaca Putih',
                'category' => 'Anorganik',
                'info' => "Kaca putih atau bening adalah jenis kaca yang paling umum digunakan untuk berbagai keperluan, dari botol minuman hingga wadah makanan. Kaca putih dapat didaur ulang tanpa batas tanpa kehilangan kualitas atau kejernihan. Daur ulang kaca putih membantu mengurangi penggunaan bahan baku baru, menghemat energi, dan mengurangi limbah di tempat pembuangan sampah.",
                'handling_info' => "- Bilas botol atau wadah kaca putih untuk menghilangkan sisa isi.\n- Pisahkan tutup atau label jika memungkinkan.\n- Kumpulkan kaca putih terpisah dari warna kaca lainnya.\n- Hindari memecahkan kaca untuk keamanan.\n- Bawa ke pusat daur ulang atau tempat pengumpulan kaca.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Tinggi - Dapat didaur ulang 100% tanpa kehilangan kualitas.',
                'decomposition_time' => 'Satu juta tahun atau lebih.',
                'reduction_tips' => "- Gunakan botol kaca yang dapat diisi ulang.\n- Pilih produk dalam kemasan kaca daripada plastik jika memungkinkan.\n- Gunakan kembali botol dan toples kaca untuk penyimpanan.\n- Dukung merek yang menggunakan kaca daur ulang.",
                'other_examples' => 'Gelas minum, toples selai, lampu bohlam (tanpa filamen)',
                'regulations' => 'Peraturan Menteri Negara Lingkungan Hidup Nomor 13 Tahun 2012 tentang Pedoman Pelaksanaan Reduce, Reuse, dan Recycle melalui Bank Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Kertas',
                'category' => 'Anorganik',
                'info' => "Kertas adalah material yang terbuat dari serat tumbuhan dan banyak digunakan untuk menulis, mencetak, dan mengemas. Limbah kertas termasuk koran, majalah, buku, kertas kantor, dan karton. Kertas dapat didaur ulang beberapa kali, meskipun kualitasnya menurun setiap kali didaur ulang. Daur ulang kertas membantu mengurangi penebangan pohon, menghemat energi, dan mengurangi limbah di tempat pembuangan sampah.",
                'handling_info' => "- Pisahkan kertas dari jenis sampah lainnya.\n- Hindari kertas yang terkontaminasi makanan atau minyak.\n- Ratakan kardus untuk menghemat ruang.\n- Pisahkan kertas berdasarkan jenisnya jika memungkinkan (koran, kardus, kertas kantor).\n- Bawa ke pusat daur ulang atau bank sampah.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Tinggi - Dapat didaur ulang menjadi berbagai produk kertas baru.',
                'decomposition_time' => '2-6 minggu untuk kertas koran, hingga beberapa bulan untuk jenis kertas lain.',
                'reduction_tips' => "- Gunakan kedua sisi kertas saat menulis atau mencetak.\n- Opt-out dari surat kabar atau majalah fisik dan beralih ke versi digital.\n- Gunakan sapu tangan kain daripada tisu kertas.\n- Hindari penggunaan kertas sekali pakai seperti serbet kertas.",
                'other_examples' => 'Amplop, kantong kertas, kartu ucapan, poster',
                'regulations' => 'Peraturan Menteri Negara Lingkungan Hidup Nomor 13 Tahun 2012 tentang Pedoman Pelaksanaan Reduce, Reuse, dan Recycle melalui Bank Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'class_name' => 'Sepatu',
                'category' => 'Anorganik',
                'info' => "Sepatu umumnya terbuat dari berbagai bahan termasuk kulit, kain, karet, dan plastik. Karena komposisi campuran ini, sepatu dapat menjadi tantangan untuk didaur ulang. Namun, banyak komponen sepatu dapat digunakan kembali atau didaur ulang jika diproses dengan benar. Sepatu bekas yang masih dalam kondisi baik dapat disumbangkan, sementara sepatu yang sudah rusak dapat diolah untuk memisahkan komponennya.",
                'handling_info' => "- Pisahkan sepatu dari limbah rumah tangga lainnya.\n- Jika masih dalam kondisi baik, sumbangkan ke badan amal atau toko barang bekas.\n- Untuk sepatu rusak, cek program take-back dari produsen sepatu.\n- Bawa ke pusat daur ulang khusus yang menerima sepatu jika tersedia.\n- Jangan membuang sepatu ke tempat sampah biasa jika memungkinkan.",
                'environmental_impact' => 'Sedang',
                'recycling_potential' => 'Sedang - Beberapa bagian dapat didaur ulang, tetapi proses pemisahan bisa rumit.',
                'decomposition_time' => '25-40 tahun, tergantung pada bahan.',
                'reduction_tips' => "- Beli sepatu berkualitas yang tahan lama.\n- Perbaiki sepatu yang rusak daripada membuangnya.\n- Pilih sepatu dengan bahan ramah lingkungan.\n- Jual atau sumbangkan sepatu yang tidak dipakai tapi masih layak.",
                'other_examples' => 'Sandal, sepatu olahraga, sepatu bot, sepatu anak-anak',
                'regulations' => 'Belum ada regulasi khusus untuk limbah sepatu di Indonesia, namun termasuk dalam Undang-Undang Nomor 18 Tahun 2008 tentang Pengelolaan Sampah',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('waste_categories')->insert($categories);
    }
}